replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  ALLOWED_HOSTS: "*"
  DEBUG: "True"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "db_user"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

secrets:
  POSTGRES_PASSWORD: ""
  SECRET_KEY: ""