apiVersion: batch/v2
kind: Job
metadata:
  name: kaniko-build
  namespace: jenkins
spec:
  template:
    spec:
      serviceAccountName: jenkins
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/blackkat02/DevOps.git#refs/heads/final-project"
        - "--destination=$(AWS_ACCOUNT_ID).dkr.ecr.us-west-2.amazonaws.com/final-project-ecr:latest"
        - "--ecr-auto-login=true"
      restartPolicy: Never