applications:
  django-app:
    namespace: "django-app"
    repoURL: "https://github.com/blackkat02/DevOps.git" 
    targetRevision: "final-project"
    path: "final-project/charts/django-app"

image:
  repository: ""
  tag: "v1.0.0"