apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: jenkins
spec:
  template:
    spec:
      serviceAccountName: jenkins
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/blackkat02/DevOps.git#refs/heads/lesson-10"
        - "--destination=882574060785.dkr.ecr.us-west-2.amazonaws.com/lesson-10-ecr:latest"
        - "--ecr-auto-login=true"
      restartPolicy: Never