apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: jenkins
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/your-username/django-app.git" # Заміни на свій репо
        - "--destination=882574060785.dkr.ecr.us-west-2.amazonaws.com/lesson-10-ecr:latest"
        volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
          secretName: kaniko-secret
          items:
            - key: .dockerconfigjson
              path: config.json