apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
spec:
  type: {{ .Values.service.type }} # З values.yaml (LoadBalancer)
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: django